<ul>
	<li>Mage::helper('core/http')-&gt;getRemoteAddr(): <span style="font-weight:bold"><?php echo Mage::helper('core/http')->getRemoteAddr();?></span></li>
	<li>$_SERVER['HTTP_CLIENT_IP']: <span style="font-weight:bold"><?php echo $_SERVER['HTTP_CLIENT_IP'];?></span></li>
	<li>$_SERVER['HTTP_X_FORWARDED_FOR']: <span style="font-weight:bold"><?php echo $_SERVER['HTTP_X_FORWARDED_FOR'];?></span></li>
</ul>